### ISSUE TITLE
Utilities.py -- Index 8 is out of bounds

### ISSUE THREAD

**Issue by nasatony** [illidanlab/urgent-care-comparative#3]
Ubuntu 16.04 / Python 3.6 / Pandas 0.22.0

100% (27599 of 27599) |########################################################################| Elapsed Time: 0:05:06 Time:  0:05:06
lactate: 1.5

100% (27599 of 27599) |########################################################################| Elapsed Time: 0:05:07 Time:  0:05:07
Done!

Preprocessing to construct X and y.
  0% (86 of 33366) |                                                                           | Elapsed Time: 0:00:00 ETA:   0:01:18Traceback (most recent call last):
  File "preprocess.py", line 422, in <module>
    X, y, Z, X48, sentences, words = preprocess(features, labels, demographics)
  File "preprocess.py", line 344, in preprocess
    los = list(one_hot([labels[s]['los_bin']], 8)[0])
  File "/home/ubuntu/Research/ucc_2019/utilities.py", line 19, in one_hot
    onehot[i, int(arr[i])]=1
IndexError: index 8 is out of bounds for axis 1 with size 8

**Comment by nasatony** [comment]
Resolved the problem by making the following modification in preprocess method:

los = list(one_hot([labels[s]['los_bin']], 8)[0])  changed to
los = list(one_hot([labels[s]['los_bin']], 9)[0])
